config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'

  get '/auth/facebook', :as => 'login'

  get '/auth/facebook/callback' => 'sessions#create'

  delete 'logout' => 'sessions#destroy', :as => 'log_out'

  resources :games, :only => [:new, :show]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :questions
  
end

app/models/game.rb
class Game < ActiveRecord::Base
  include QuestionModules::Fetcher

  belongs_to :show
  has_many :questions, through: :show
  has_many :prizes, -> { uniq }, through: :show
  has_many :rounds, -> { uniq }, through: :show
  has_many :categories, -> { uniq }, through: :show

  has_many :user_games
  has_many :users, through: :user_games

end

app/models/prize.rb
class Prize < ActiveRecord::Base
  has_many :questions
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :show
  belongs_to :prize
  belongs_to :round
  belongs_to :category

end

app/models/round.rb
class Round < ActiveRecord::Base
  has_many :questions
  
end

app/models/show.rb
class Show < ActiveRecord::Base
  include QuestionModules::Fetcher
  
  has_many :questions
  has_many :prizes, -> { uniq }, through: :questions
  has_many :rounds, -> { uniq }, through: :questions
  has_many :categories, -> { uniq }, through: :questions

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_games
  has_many :games, through: :user_games

  def self.find_or_create_from_auth_hash(auth)
    found = User.where(:provider => auth["provider"], :uid => auth["uid"])
    return found[0] if !found.empty?
    user = self.create(
      :provider => auth["provider"],
      :uid => auth["uid"],
      :name => auth["info"]["name"],
      :first_name => auth["info"]["first_name"],
      :last_name => auth["info"]["last_name"],
      :image => auth["info"]["image"]
    )
  end

end

app/models/user_game.rb
class UserGame < ActiveRecord::Base
  belongs_to :user
  belongs_to :game

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def show
    @game = Game.find(params[:id])
    @data = @game.jeopardy 
  end

  def new
    @game = Game.new(:show_id => Show.all.sample.id)
    if @game.save
      UserGame.create(:user_id => current_user.id, :game_id => @game.id)
      redirect_to game_path(@game)
    else
      redirect_to "/", error: "An error occurred. We apologize for the inconvienince."
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/show.html.erb
<div class="row">
  <% @data.each do |category, questions| %>
    <div class="col-md-2 game-card category-card">
      <div class="category-card">
        <h4><%= category.upcase %><h4>
      </div>

      <% questions.each do |question| %>
        <div class="row">
          <div class="col-xs-12 game-card question-card"  data-answer="<%= question.answer %>" data-question="<%= question.text %>">
            <h1>$<%= question.prize.amount %><h1>
          </div>
        </div>
      <% end %>

    </div>
  <% end %>
</div>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Jeopardy</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="#">Left Side</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Right Side</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Attendance</title>
    <link rel="icon" type="image/png" href="/favicon.ico" />
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- custom files/sheets -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => false  %>

    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
  <body>
    
    <%= render "layouts/nav_bar" %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/static_pages/_logged_in.html.erb
<div class="jumbotron">
  <h1>Welcome <%= current_user.first_name %>!</h1>
  <span>
    <%= link_to "Play", new_game_path, :class => 'btn btn-primary btn-lg' %>
  </span>
  <span>
    <%= link_to "Logout", log_out_path, :method => :delete, :class => 'btn btn-info btn-lg' %>
  </span>
</div>

app/views/static_pages/_login.html.erb
<div class="jumbotron">
  <h1><%= link_to "<i class=\"fa fa-facebook-square\"></i> Login".html_safe, login_path, :class => 'btn btn-primary btn-lg' %></h1>
</div>

app/views/static_pages/home.html.erb
<% if current_user %>
  <%= render "logged_in" %>
<% else %>
  <%= render "login" %>
<% end %>